name: Fetch SVGs from Figma

on:
  repository_dispatch:
    types: [icons_updated]

env:
  NODE_VERSION: '21.x'

jobs:
  fetch_icons:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install Dependencies
        run: npm i

      - name: Extract latest from Figma
        run: npm run fetch-icons
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '🤖 Figma Icons Update'
