name: Fetch SVGs from Figma

on:
  repository_dispatch:
    types: [icons_updated]

# So only the latest run is executed. Used to avoid concurrency issues as Figma webhook can be spammy at times.
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  fetch_icons:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: 21

      - name: Install Dependencies
        run: npm i

      - name: Fetch icons from Figma
        run: npm run fetch-icons
        env:
          FIGMA_TOKEN: ${{ secrets.FIGMA_TOKEN }}

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          default_author: github_actions
          message: '🤖 Figma Icons Update'
